Add option to show only closed cases.
mysociety/noiseworks pull request #147
Opened 2022-09-29 18:12 UTC by neprune

Issue: https://github.com/mysociety/societyworks/issues/3115
Still trying to get the default state to be to include the closed cases...

2022-10-03 16:36 UTC, dracos requested changes
One query is all :)

2022-10-04 08:51 UTC, neprune commented on cases/filters.py
> +        empty_label=None,
Annoyingly a `ChoiceFilter` doesn't get run when no selection is made, even with an empty value, so closed cases were always included. Setting an initial value was my work around for this.

Another approach could be to make `empty_label` `Included` and have the default case view include closed cases but I thought we'd probably not want that.

Another another approach could be a "Closed only" checkbox in addition to the existing "Include closed" checkbox with the relevant JS to make that sane. I originally had this but thought it was a bit of a clumsy UX.

2022-10-04 08:56 UTC, dracos commented on cases/filters.py
> +        empty_label=None,
"Annoyingly a ChoiceFilter doesn't get run when no selection is made" - ah, fair enough then!

2022-10-04 08:56 UTC, dracos approved these changes

2022-10-24 09:34 UTC, merged