Add 'case_worker' and 'case_reporter' groups to lock down staff permissions.
mysociety/noiseworks pull request #154
Opened 2022-11-14 11:20 UTC by neprune

Issues: https://github.com/mysociety/societyworks/issues/3117 https://github.com/mysociety/societyworks/issues/3122

2022-11-16 17:16 UTC, dracos requested changes
A few tiny things is all, looks good :)

2022-11-16 17:16 UTC, dracos commented on cases/migrations/0038_make_all_staff_case_workers.py
> +    case_workers.save()
I don't think this save is needed, you haven't changed the group object at all

2022-11-17 12:46 UTC, neprune commented on cases/migrations/0037_add_staff_groups.py
> +    _, _ = Group.objects.get_or_create(name="case_reporters")
Thinking about this more I thought it would be cleaner to just drop this group and just have case workers and non case workers for now.

2022-11-17 12:46 UTC, neprune commented
@dracos Apologies for the force-push, worked out easier with removing the 'internal only' commit

2022-12-15 14:57 UTC, merged